services:
  db:
    image: postgres:16
    container_name: expense-manager-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: enrique
      POSTGRES_PASSWORD: 2540712
      POSTGRES_DB: expense_manager
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: