"""add created_at to transactions

Revision ID: 9ab4a84967b3
Revises: 687e21151f18
Create Date: 2026-09-08 21:03:07.551407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ab4a84967b3'
down_revision: Union[str, None] = '687e21151f18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('transactions', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column(
    'transactions',
    sa.Column('created_at', sa.DateTime(), nullable=True))

    op.execute(
        "UPDATE transactions SET created_at = CURRENT_TIMESTAMP"
    )

    op.alter_column(
        'transactions',
        'created_at',
        nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'created_at')
    # ### end Alembic commands ###
